package com.example.recallify.view.common.function

import android.os.Build
import android.widget.Toast
import androidx.annotation.RequiresApi
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.platform.LocalContext
import com.vanpra.composematerialdialogs.MaterialDialog
import com.vanpra.composematerialdialogs.MaterialDialogState
import com.vanpra.composematerialdialogs.datetime.date.datepicker
import com.vanpra.composematerialdialogs.rememberMaterialDialogState
import java.text.SimpleDateFormat
import java.time.LocalDate
import java.util.*

/**
 * Create a date picking calendar in a dialog container, can be used in various date picking option.
 * Used in the Daily diary feeds section.
 *
 * @param dateState The state of the date being selected
 * @return The date picked from the calendar
 * @author Hassan
 * */
@Composable
fun datePicker(dateState: MaterialDialogState): String {
    /**
     * The context of the application generated by the application Context. The context is locally
     * called from inside a composable console as the class context will be referred as
     * ``` markdown
     * this@<Classname!>
     * ```
     * The class in which the context is gotten from at the time the program was launched.
     *
     * @author Hassan
     * */
    val context = LocalContext.current

    /**
     * The state check of the picked date. Checks the build version of the user's phone.
     *
     * @author Hassan
     * */
    var pickedDate by remember {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            mutableStateOf(LocalDate.now())
        } else {
            TODO("The mobile is not compatible")
        }
    }

    MaterialDialog(
        dialogState = dateState,
        buttons = {
            positiveButton(
                text = "Ok",
                onClick = {
                    Toast.makeText(
                        context,
                        "Filtering",
                        Toast.LENGTH_LONG
                    ).show()
                }
            )
            negativeButton(text = "Cancel")
        },
        content = {
            datepicker(
                initialDate = LocalDate.now(),
                title = "Pick a Date"
            ) {
                pickedDate = it
            }
        }
    )
    return pickedDate.toString()
}

/**
 * Create a date picking calendar in a dialog container, can be used in various date picking option.
 * Used in the Daily diary feeds section.
 *
 * @author Hassan
 * */
@RequiresApi(Build.VERSION_CODES.O)
@Composable
fun datePicker(): String {

    /**
     * The context of the application generated by the application Context. The context is locally
     * called from inside a composable console as the class context will be referred as
     * ``` markdown
     * this@<Classname!>
     * ```
     * The class in which the context os gotten from at the time the program was launched
     * @author Hassan
     * */
    val context = LocalContext.current

    /**
     * The picked date of the dialog state.
     *
     * @author Hassan
     * */
    var pickedDate by remember {
        mutableStateOf(LocalDate.now())
    }

    /**
     * The date state of the dialog which is picked.
     *
     * @author Hassan
     * */
    val dateDialogState = rememberMaterialDialogState()

    Button(
        onClick = {
            dateDialogState.show()
        },
        content = {
            Text(text = "Pick a Date")
        }
    )

    MaterialDialog(
        dialogState = dateDialogState,
        buttons = {
            positiveButton(
                text = "Ok",
                onClick = {
                    Toast.makeText(
                        context,
                        "Clicked Ok",
                        Toast.LENGTH_LONG
                    ).show()
                }
            )
            negativeButton(
                text = "Cancel"
            )

        },
        content = {
            datepicker(
                initialDate = LocalDate.now(),
                title = "Pick a Date"
            ) {
                pickedDate = it
            }
        }
    )

    return pickedDate.toString()

}

/**
 * This gets the current date of when a log or activity is being made.
 *
 * @return The formatted date in format **YYYY-MM-DD, year-month-date**.
 *
 * @author Hassan A
 * */
fun getCurrentDate(): String {
    val date = Date().time
    val formatter = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
    return formatter.format(date)
}
